### PR TITLE
Modify translation snippet.

### PR DESCRIPTION
**Pull request by jernejdroljc**

### CODE REVIEW

**Comment by dejanstrancar** [comment]
@jernejdroljc @matjazzorko zakaj je slo to v master in ne v develop?

**Comment by dejanstrancar** [comment]
samo develop se lahko merga v masterja,...

**Comment by jernejdroljc** [comment]
@dejanstrancar Hmm, mogoče sem jaz odprl pomotoma Feature iz masterja? Ker po postopku sodeče, sem delal isto kot prej na našem repositoryju.

**Comment by dejanstrancar** [comment]
@jernejdroljc all branches are created from develop which is ahead or equal to master anyway.
but since you created that one from master you can still make PR to develop.
i would suggest that you revert that PR, and merge it to develop. no reviews needs to be done since it was already reviewed.

**Pull request merged**
